### ISSUE TITLE
string is not a function 

### ISSUE THREAD

**Issue by akk001** [eisenbraun/columns#3]
my Code:

 $.ajax({
                type: "post",
                url: "Ajax_Actions/Rep_AjaxActions.aspx/GetLookupData2",
                data: "{'EncryptedUserID':'" + EncryptedUserID + "'," +
                     "'LangSuffix':'" + LangSuffix + "'," +
                     "'EntityTable':'" + EntityTable + "'," +  
                     "'FilterValue':'" + FilterValue + "'," +
                     "'Status':'" + Status + "'}",
                contentType: "application/json; charset=utf-8",
                dataType: "json",
                success: function (json) {
                    try {  
                        var jsondata = json.d;  
                        div_mohdata = $('#div_mohdata').columns({
                            data: jsondata,
                        });
                    } catch (ex) { $.unblockUI(); alert(ex.message);}
                    $.unblockUI();
                },
                failure: function () {
                    alert("error")
                    $.unblockUI();
                }
            });
# 

At this point 
  div_mohdata = $('#div_mohdata').columns({
                            data: jsondata,
                        });

I am getting error "String is not a function. "

When i use the first example( inline json data) of your examples section it works fine but the same data is giving error when bought from external source in the above manner, " String is not a function";

Please help me I am new to jquery with very little debugging skills. 

Regards

Khan.

**Comment by eisenbraun** [comment]
Khan,
I looked over the code you send me. Nothing jumped out at me as being the problem, but I did see a couple of things. In your Ajax call you are using "failure" setting. I believe you want "error" instead. In the Columns settings, there is a trailing comma after "data: jsondata" that can cause problems in IE. 

Typically when I see a "String is not a function" error, it means the the same variable name was accidentally initialized twice. From the Error Console, are you able to see which function is being evaluated? Which browser are you using? I believe Firefox or Safari will provide a little more information about the problem.

Also, since you said it worked fine when you used the JSON data inline, double check to make sure your data is coming back from the Ajax as you expected. 

I will keep looking over my code to make there isn't a bug there. Any additional information you could provide would be helpful. 

Let me know if you have any further questions. 

Thanks for using Columns.
Michael

**Comment by akk001** [comment]
Actually the failure setting it to catch the thrown exception from business layer. 
I tried removing the comma after "data: jsondata" but no difference. 
Also checked that there is no other variable in use with the name jsondata
I am using google chorome
The following inline code worked fine for me

var json = [{"ID":1001,"Bank Code":1001,"Bank Name":"البنك الأهلي التجاري","Comments":"Initial Data Entry","Status":"\u003cFONT color=#4CC417\u003e\u003cSTRONG\u003eActive\u003c/STRONG\u003e\u003c/FONT\u003e","Timestamp Latin":"\/Date(1142842080000)\/","Timestamp Hijri":14270220,"IMID":3051,"IM Timestamp":"31/01/2011 14:32"},{"ID":1002,"Bank Code":1002,"Bank Name":"بنك الرياض","Comments":"Initial Data Entry","Status":"\u003cFONT color=#4CC417\u003e\u003cSTRONG\u003eActive\u003c/STRONG\u003e\u003c/FONT\u003e","Timestamp Latin":"\/Date(1142842080000)\/","Timestamp Hijri":14270220,"IMID":3056,"IM Timestamp":"31/01/2011 14:32"},{"ID":1003,"Bank Code":1003,"Bank Name":"البنك العربي الوطني","Comments":"Initial Data Entry","Status":"\u003cFONT color=#4CC417\u003e\u003cSTRONG\u003eActive\u003c/STRONG\u003e\u003c/FONT\u003e","Timestamp Latin":"\/Date(1142842080000)\/","Timestamp Hijri":14270220,"IMID":3061,"IM Timestamp":"31/01/2011 14:32"}]
                    $('#div_mohdata').columns({
                        data: json
                    });

but when the same exact data is bought from an external data source the problem occurs.

**Comment by akk001** [comment]
please help me solve the mentioned problem. 

Regards

Anees Khan.

**Comment by akk001** [comment]
Finally I solved the problem. the json output was not in the form of an array hence the problem.
