### ISSUE TITLE
Issue loading external JSON with Chrome

### ISSUE THREAD

**Issue by AlexandreHery** [eisenbraun/columns#9]
Hi,

When I go on your website with my version of Chrome, I don't have any problem seeing all your tables. However, when I create the page on my computer and then visualize on Chrome, I can't see anything. It works on IE and Firefox but not Chrome. I am wondering why.
Second question, I added the folder to an internal server with local links and now, none of the browsers can read the JSON file. any idea, please ?

Thank you a lot for this useful tool,
Alex

**Comment by eisenbraun** [comment]
Alex, 
Sorry it took me so long to respond.  Make sure that everything is running on the same domain name. Since you are trying to access the JSON using AJAX and you are not allow to make cross domain calls, it would cause the AJAX to fail.  Check your browser console to be sure. 

Again sorry for the delay.
Michael
